theme_name: ASIBUKA Group Theme
# ------------------------------
# 🌐 Theme Information
# 1. All pages and posts valid AMPHTML
# 2. All pages and posts valid CSS3
# 3. All pages and posts valid HTML5
# 4. All pages and posts passed the Pagespeed Insight Test
# 5. All pages and posts passed the Lighthouse Test
# 6. All pages and posts are well-layouted
# 7. All pages and posts have well configuration for SEO
# 8. All pages and posts have well-structured Schema metadata
# 9. All pages and posts 
# ------------------------------
# ------------------------------
# 🌐 Default Value
# ------------------------------
title: "ASIBUKA Group"
description: "ASIBUKA Group adalah usaha yang bergerak di bidang investasi UMKM berbasis teknologi."
keywords: "ASIBUKA, ASIBUKA Group, Bisnis, Investasi, UMKM"
robots: "index, follow"
baseurl: ""
url: "https://www.asibuka.com"
image: "/assets/img/ASIBUKA-Blue.webp"
date: 2023-06-19 00:00:05
timezone: "Asia/Jakarta"
lang: "id"
categories: [-]
tags: [ASIBUKA, ASIBUKA Blog]
# ------------------------------
# 👤 Author Info
# ------------------------------
author: "ASIBUKA Group"
email: "admin@asibuka.com"
# ------------------------------
# 🗂 Pagination
# ------------------------------
permalink: /:title/
# ------------------------------
# 🗂 Collections
# ------------------------------
collections:
  posts:
    output: true
  ad-networks:
    output: true
  asibuka-logistics:
    output: true
  products:
    output: true
  statics:
    output: true
  webtools:
    output: true
# ------------------------------
# Default Value
# ------------------------------
defaults:
  - scope:
      path: ""
      type: "js"
    values:
      layout: null
# ------------------------------
# 🌐 Markdown Settings
# ------------------------------
highlighter: rogue
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rogue
  smart_quotes: ["apos", "apos", "quot", "quot"]
# ------------------------------
# 🌐 Comments
# ------------------------------
comments: false
disqus_shortname: "asibukagroup"
# ------------------------------
# 🌐 Other Settings
# ------------------------------
future: true
safe: false
include:
  - amp
  - sw.js
  - sw.js.liquid
sameAs:
  - name: Twitter
    url: "https://twitter.com/asibukagroup"
    icon: "/assets/icons/twitter.svg"
  - name: Facebook
    url: "https://www.facebook.com/asibukaofficial"
    icon: "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 448 512'><path d='M64 32C28.7 32 0 60.7 0 96V416c0 35.3 28.7 64 64 64h98.2V334.2H109.4V256h52.8V222.3c0-87.1 39.4-127.5 125-127.5c16.2 0 44.2 3.2 55.7 6.4V172c-6-.6-16.5-1-29.6-1c-42 0-58.2 15.9-58.2 57.2V256h83.6l-14.4 78.2H255V480H384c35.3 0 64-28.7 64-64V96c0-35.3-28.7-64-64-64H64z'/></svg>"
  - name: YouTube
    url: "https://www.youtube.com/@ASIBUKAGroup"
    icon: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"><path d="M549.7 124.1c-6.3-23.7-24.8-42.3-48.3-48.6C458.8 64 288 64 288 64S117.2 64 74.6 75.5c-23.5 6.3-42 24.9-48.3 48.6-11.4 42.9-11.4 132.3-11.4 132.3s0 89.4 11.4 132.3c6.3 23.7 24.8 41.5 48.3 47.8C117.2 448 288 448 288 448s170.8 0 213.4-11.5c23.5-6.3 42-24.2 48.3-47.8 11.4-42.9 11.4-132.3 11.4-132.3s0-89.4-11.4-132.3zm-317.5 213.5V175.2l142.7 81.2-142.7 81.2z"/></svg>'
  - name: GitHub
    url: "https://github.com/asibukagroup"
    icon: "/assets/icons/github.svg"
# ------------------------------
# Navigation links
# ------------------------------
nav_links:
  Beranda: "/"
  Cari: "/search/"
  Blog: "/blog/"
  Informasi Resmi: "/page/"
  Produk: "/produk/"
  Tentang Kami: "/page/tentang-kami/"
# ------------------------------
# Plugins
# ------------------------------
plugins_dir: _plugins
plugins:
  - jekyll-archives
  - jekyll-sitemap
  - ./_plugins/amp_generator.rb
  - ./_plugins/minifier.rb
  - ./_plugins/toc_generator.rb
whitelist:
  - jekyll-archives
  - jekyll-sitemap
  - ./_plugins/amp_generator.rb
  - ./_plugins/minifier.rb
  - ./_plugins/toc_generator.rb
# ------------------------------
# Jekyll Archives
# ------------------------------
jekyll-archives:
  enabled:
    - year
    - month
    - categories
    - tags
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    tag: '/tag/:name/'
    category: '/kategori/:name/'